# Use an official Python runtime as a base image
FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY ../ .

# Expose the port Gunicorn will run on
EXPOSE 5000

# Command to start Gunicorn with multiple workers
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
